sculpin_content_types:
    posts:
        enabled: false
    editions:
        type: path
        singular_name: edition
        permalink: :filename/
    emails:
        type: path
        singular_name: email
        permalink: emails/:filename/
    articles:
        type: path
        singular_name: article
        permalink: :filename/
    previews:
        type: path
        singular_name: preview
        permalink: preview/:filename/
